joy_teleop:
  ros__parameters:
    publish_stopped_twist: true
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: bumperbot_controller/cmd_vel
      deadman_buttons: [5]
      autorepeat_rate: 100.0
      coalesce_interval_ms: 0
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 8.0
          offset: 0.0